/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventas;

/**
 *
 * @author REYNALDO
 */
public class panelGiros extends javax.swing.JPanel {

    /**
     * Creates new form panelGiros
     */
    public panelGiros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelEmisor = new javax.swing.JPanel();
        lblTipoDocumentoE = new javax.swing.JLabel();
        lblNombresE = new javax.swing.JLabel();
        lblTelefonoE = new javax.swing.JLabel();
        txtNombresE = new javax.swing.JTextField();
        txtTelefonoE = new javax.swing.JTextField();
        lblNumDocumentoE = new javax.swing.JLabel();
        lblApellidosE = new javax.swing.JLabel();
        lblEmailE = new javax.swing.JLabel();
        txtNumDocumentoE = new javax.swing.JTextField();
        txtApellidosE = new javax.swing.JTextField();
        txtEmailE = new javax.swing.JTextField();
        lblDireccionE = new javax.swing.JLabel();
        txtDireccionE = new javax.swing.JTextField();
        lblUbigeoE = new javax.swing.JLabel();
        txtUbigeoE = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lblDatosEmisor = new javax.swing.JLabel();
        cboTipoDocumentoE = new javax.swing.JComboBox<>();
        panelReceptor = new javax.swing.JPanel();
        lblTipoDocumentoR = new javax.swing.JLabel();
        lblNombresR = new javax.swing.JLabel();
        lblTelefonoR = new javax.swing.JLabel();
        txtNombresR = new javax.swing.JTextField();
        txtTelefonoR = new javax.swing.JTextField();
        lblNumDocumentoR = new javax.swing.JLabel();
        lblApellidosR = new javax.swing.JLabel();
        lblEmailR = new javax.swing.JLabel();
        txtNumDocumentoR = new javax.swing.JTextField();
        txtApellidosR = new javax.swing.JTextField();
        txtEmailR = new javax.swing.JTextField();
        lblDireccionR = new javax.swing.JLabel();
        txtDireccionR = new javax.swing.JTextField();
        lblUbigeoR = new javax.swing.JLabel();
        txtUbigeoR = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        lblDatosReceptor = new javax.swing.JLabel();
        cboTipoDocumentoR = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        lblTipoMoneda = new javax.swing.JLabel();
        lblCantidadEnvio = new javax.swing.JLabel();
        txtTipoMoneda = new javax.swing.JTextField();
        txtCantidadEnvio = new javax.swing.JTextField();
        lblDireccionEnvio = new javax.swing.JLabel();
        lblPrecioEnvio = new javax.swing.JLabel();
        txtDireccionEnvio = new javax.swing.JTextField();
        txtPrecioEnvio = new javax.swing.JTextField();
        lblFechaEnvio = new javax.swing.JLabel();
        lblRazonSocialEnvio = new javax.swing.JLabel();
        txtRazonSocialEnvio = new javax.swing.JTextField();
        lblOrigenEnvio = new javax.swing.JLabel();
        lblDestinoEnvio = new javax.swing.JLabel();
        calendarFechaEnvio = new com.toedter.calendar.JDateChooser();
        cboOrigenEnvio = new javax.swing.JComboBox<>();
        cboDestinoEnvio = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        lblDatosEnvio = new javax.swing.JLabel();
        btnGuardarEnvio = new javax.swing.JButton();
        btnNuevoEnvio = new javax.swing.JButton();
        SubTotalEnvio = new javax.swing.JLabel();
        TotalEnvio = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblEnvioGiros = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setPreferredSize(new java.awt.Dimension(1326, 805));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1180, 710));
        jPanel1.setRequestFocusEnabled(false);

        panelEmisor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblTipoDocumentoE.setText("TIPO DOCUMENTO");

        lblNombresE.setText("NOMBRES");

        lblTelefonoE.setText("TELEFONO");

        lblNumDocumentoE.setText("N° DOCUMENTO");

        lblApellidosE.setText("APELLIDOS");

        lblEmailE.setText("EMAIL");

        lblDireccionE.setText("DIERECCION");

        lblUbigeoE.setText("UBIGEO");

        jPanel5.setBackground(new java.awt.Color(102, 255, 255));

        lblDatosEmisor.setBackground(new java.awt.Color(102, 255, 255));
        lblDatosEmisor.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblDatosEmisor.setText("DATOS EMISOR");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDatosEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDatosEmisor, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        cboTipoDocumentoE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Dni", "Carnet Ext.", "Pasaporte" }));

        javax.swing.GroupLayout panelEmisorLayout = new javax.swing.GroupLayout(panelEmisor);
        panelEmisor.setLayout(panelEmisorLayout);
        panelEmisorLayout.setHorizontalGroup(
            panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmisorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccionE, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccionE, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombresE, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombresE, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTipoDocumentoE, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoDocumentoE, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumDocumentoE)
                    .addComponent(txtEmailE)
                    .addComponent(lblNumDocumentoE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblApellidosE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmailE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUbigeoE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelEmisorLayout.createSequentialGroup()
                        .addComponent(txtUbigeoE, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addComponent(txtApellidosE))
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelEmisorLayout.setVerticalGroup(
            panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmisorLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoDocumentoE)
                    .addComponent(lblNumDocumentoE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumDocumentoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTipoDocumentoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidosE)
                    .addComponent(lblNombresE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombresE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidosE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelEmisorLayout.createSequentialGroup()
                        .addGroup(panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmailE)
                            .addComponent(lblTelefonoE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelEmisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelEmisorLayout.createSequentialGroup()
                                .addComponent(lblDireccionE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDireccionE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelEmisorLayout.createSequentialGroup()
                                .addComponent(lblUbigeoE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUbigeoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelEmisorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtTelefonoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        panelReceptor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelReceptor.setPreferredSize(new java.awt.Dimension(538, 302));

        lblTipoDocumentoR.setText("TIPO DOCUMENTO");

        lblNombresR.setText("NOMBRES");

        lblTelefonoR.setText("TELEFONO");

        lblNumDocumentoR.setText("N° DOCUMENTO");

        lblApellidosR.setText("APELLIDOS");

        lblEmailR.setText("EMAIL");

        txtApellidosR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosRActionPerformed(evt);
            }
        });

        lblDireccionR.setText("DIRECCION");

        lblUbigeoR.setText("UBIGEO");

        jPanel6.setBackground(new java.awt.Color(102, 255, 255));

        lblDatosReceptor.setBackground(new java.awt.Color(102, 255, 255));
        lblDatosReceptor.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblDatosReceptor.setText("DATOS RECEPTOR");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDatosReceptor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDatosReceptor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        cboTipoDocumentoR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Dni", "Carnet Ext.", "Pasaporte" }));

        javax.swing.GroupLayout panelReceptorLayout = new javax.swing.GroupLayout(panelReceptor);
        panelReceptor.setLayout(panelReceptorLayout);
        panelReceptorLayout.setHorizontalGroup(
            panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReceptorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccionR, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDireccionR)
                    .addComponent(txtTelefonoR, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonoR)
                    .addComponent(txtNombresR, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombresR)
                    .addComponent(cboTipoDocumentoR, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoDocumentoR))
                .addGap(51, 51, 51)
                .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumDocumentoR)
                    .addComponent(txtEmailR)
                    .addComponent(txtApellidosR)
                    .addGroup(panelReceptorLayout.createSequentialGroup()
                        .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUbigeoR)
                            .addComponent(lblApellidosR)
                            .addComponent(lblNumDocumentoR)
                            .addComponent(lblEmailR)
                            .addComponent(txtUbigeoR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelReceptorLayout.setVerticalGroup(
            panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReceptorLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoDocumentoR)
                    .addComponent(lblNumDocumentoR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumDocumentoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTipoDocumentoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidosR)
                    .addComponent(lblNombresR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombresR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidosR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReceptorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtTelefonoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelReceptorLayout.createSequentialGroup()
                        .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmailR)
                            .addComponent(lblTelefonoR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmailR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelReceptorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReceptorLayout.createSequentialGroup()
                        .addComponent(lblDireccionR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDireccionR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelReceptorLayout.createSequentialGroup()
                        .addComponent(lblUbigeoR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUbigeoR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setPreferredSize(new java.awt.Dimension(1086, 207));

        lblTipoMoneda.setText("TIPO DE MONEDA");

        lblCantidadEnvio.setText("CANTIDAD");

        lblDireccionEnvio.setText("DIRECCION");

        lblPrecioEnvio.setText("PRECIO DE ENVIO ");

        txtDireccionEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionEnvioActionPerformed(evt);
            }
        });

        txtPrecioEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioEnvioActionPerformed(evt);
            }
        });

        lblFechaEnvio.setText("FECHA DE ENVIO");

        lblRazonSocialEnvio.setText("RAZON SOCIAL");

        lblOrigenEnvio.setText("ORIGEN");

        lblDestinoEnvio.setText("DESTINO");

        cboOrigenEnvio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Ica", "Pisco", "Chincha", "Cañete", "Lima", "Palpa", "Nazca", "Arequipa", "Juliaca", "Huancayo", "Ayacucho", "Huaraz" }));

        cboDestinoEnvio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Ica", "Pisco", "Chincha", "Cañete", "Lima", "Palpa", "Nazca", "Arequipa", "Juliaca", "Huancayo", "Ayacucho", "Huaraz" }));

        jPanel7.setBackground(new java.awt.Color(102, 255, 255));

        lblDatosEnvio.setBackground(new java.awt.Color(102, 255, 255));
        lblDatosEnvio.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblDatosEnvio.setText("DATOS DE ENVIO");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDatosEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(lblDatosEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidadEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDireccionEnvio)
                    .addComponent(txtPrecioEnvio)
                    .addComponent(lblDireccionEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrecioEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addGap(103, 103, 103)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFechaEnvio)
                    .addComponent(txtRazonSocialEnvio)
                    .addComponent(lblRazonSocialEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calendarFechaEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                .addGap(103, 103, 103)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblOrigenEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDestinoEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboDestinoEnvio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboOrigenEnvio, 0, 166, Short.MAX_VALUE))
                .addGap(0, 38, Short.MAX_VALUE))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoMoneda)
                            .addComponent(lblDireccionEnvio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipoMoneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccionEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidadEnvio)
                            .addComponent(lblPrecioEnvio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCantidadEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaEnvio)
                            .addComponent(lblOrigenEnvio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calendarFechaEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboOrigenEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRazonSocialEnvio)
                            .addComponent(lblDestinoEnvio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRazonSocialEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboDestinoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 40, Short.MAX_VALUE))
        );

        btnGuardarEnvio.setBackground(new java.awt.Color(102, 255, 255));
        btnGuardarEnvio.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnGuardarEnvio.setText("GUARDAR");

        btnNuevoEnvio.setBackground(new java.awt.Color(102, 255, 255));
        btnNuevoEnvio.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        btnNuevoEnvio.setText("NUEVO");
        btnNuevoEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoEnvioActionPerformed(evt);
            }
        });

        SubTotalEnvio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        SubTotalEnvio.setText("SUB TOTAL :");

        TotalEnvio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TotalEnvio.setText("TOTAL :");

        jPanel8.setBackground(new java.awt.Color(102, 255, 255));

        lblEnvioGiros.setFont(new java.awt.Font("Roboto Black", 1, 18)); // NOI18N
        lblEnvioGiros.setText("ENVIO DE GIROS");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(lblEnvioGiros, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEnvioGiros, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnGuardarEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135)
                .addComponent(btnNuevoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SubTotalEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelEmisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelReceptor, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelEmisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelReceptor, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubTotalEnvio))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardarEnvio)
                        .addComponent(btnNuevoEnvio)
                        .addComponent(TotalEnvio)))
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidosRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosRActionPerformed

    private void txtDireccionEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionEnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionEnvioActionPerformed

    private void txtPrecioEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioEnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioEnvioActionPerformed

    private void btnNuevoEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoEnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoEnvioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SubTotalEnvio;
    private javax.swing.JLabel TotalEnvio;
    private javax.swing.JButton btnGuardarEnvio;
    private javax.swing.JButton btnNuevoEnvio;
    private com.toedter.calendar.JDateChooser calendarFechaEnvio;
    private javax.swing.JComboBox<String> cboDestinoEnvio;
    private javax.swing.JComboBox<String> cboOrigenEnvio;
    private javax.swing.JComboBox<String> cboTipoDocumentoE;
    private javax.swing.JComboBox<String> cboTipoDocumentoR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblApellidosE;
    private javax.swing.JLabel lblApellidosR;
    private javax.swing.JLabel lblCantidadEnvio;
    private javax.swing.JLabel lblDatosEmisor;
    private javax.swing.JLabel lblDatosEnvio;
    private javax.swing.JLabel lblDatosReceptor;
    private javax.swing.JLabel lblDestinoEnvio;
    private javax.swing.JLabel lblDireccionE;
    private javax.swing.JLabel lblDireccionEnvio;
    private javax.swing.JLabel lblDireccionR;
    private javax.swing.JLabel lblEmailE;
    private javax.swing.JLabel lblEmailR;
    private javax.swing.JLabel lblEnvioGiros;
    private javax.swing.JLabel lblFechaEnvio;
    private javax.swing.JLabel lblNombresE;
    private javax.swing.JLabel lblNombresR;
    private javax.swing.JLabel lblNumDocumentoE;
    private javax.swing.JLabel lblNumDocumentoR;
    private javax.swing.JLabel lblOrigenEnvio;
    private javax.swing.JLabel lblPrecioEnvio;
    private javax.swing.JLabel lblRazonSocialEnvio;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTelefonoE;
    private javax.swing.JLabel lblTelefonoR;
    private javax.swing.JLabel lblTipoDocumentoE;
    private javax.swing.JLabel lblTipoDocumentoR;
    private javax.swing.JLabel lblTipoMoneda;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUbigeoE;
    private javax.swing.JLabel lblUbigeoR;
    private javax.swing.JPanel panelEmisor;
    private javax.swing.JPanel panelReceptor;
    private javax.swing.JTextField txtApellidosE;
    private javax.swing.JTextField txtApellidosR;
    private javax.swing.JTextField txtCantidadEnvio;
    private javax.swing.JTextField txtDireccionE;
    private javax.swing.JTextField txtDireccionEnvio;
    private javax.swing.JTextField txtDireccionR;
    private javax.swing.JTextField txtEmailE;
    private javax.swing.JTextField txtEmailR;
    private javax.swing.JTextField txtNombresE;
    private javax.swing.JTextField txtNombresR;
    private javax.swing.JTextField txtNumDocumentoE;
    private javax.swing.JTextField txtNumDocumentoR;
    private javax.swing.JTextField txtPrecioEnvio;
    private javax.swing.JTextField txtRazonSocialEnvio;
    private javax.swing.JTextField txtTelefonoE;
    private javax.swing.JTextField txtTelefonoR;
    private javax.swing.JTextField txtTipoMoneda;
    private javax.swing.JTextField txtUbigeoE;
    private javax.swing.JTextField txtUbigeoR;
    // End of variables declaration//GEN-END:variables
}
